spring:
  datasource:
    url: jdbc:mysql://localhost:3306/saqieblog_db
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ------
    password: ------
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
logging:
  level:
    org:
      hibernate:
        SQL: debug

